name: Keepalive 24/7 (90m cycle)

# Chạy theo 2 cron entries để cover mỗi 90 phút:
on:
  schedule:
    - cron: '0 0,3,6,9,12,15,18,21 * * *'    # at 00:00,03:00,06:00,... (minute 0)
    - cron: '30 1,4,7,10,13,16,19,22 * * *'  # at 01:30,04:30,07:30,...
  workflow_dispatch: # cho phép kick tay (manual)

jobs:
  run-long-script:
    runs-on: ubuntu-latest
    timeout-minutes: 95        # bảo đảm job bị kill nếu vượt 95 phút
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run long script with timeout (~80 minutes)
        # 'timeout' sẽ kill process sau 80 phút (80m). Điều chỉnh theo nhu cầu.
        run: |
          echo "Starting long-run job (max 80 minutes)..."
          # nếu bạn dùng Windows-specific commands, thay runner hoặc dùng windows-latest
          timeout 80m python my_script.py || echo "Script ended or timed out."

      - name: Upload result artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: keepalive-logs
          path: |
            result.log
            build_log.txt
