workflows:
  macos_vps_247:
    name: "macOS M4 VPS Loop Runner"
    max_build_duration: 720  # tối đa 12h/lần build (Codemagic giới hạn)
    instance_type: mac_mini_m4  # hợp lệ theo enum chính thức
    environment:
      vars:
        LOOP_FILE: "loop.py"
        PERSIST_PATH: "/Users/builder/.persist_data"
      xcode: latest
      # python không phải field hợp lệ — dùng shell để cài Python thay thế
    triggering:
      events:
        - push  # hợp lệ; dùng push thay cho manual
    scripts:
      - name: 🧱 Chuẩn bị môi trường
        script: |
          echo "=== Cài Python và setup môi trường ==="
          brew install python@3.12 || echo "Python đã có sẵn"
          mkdir -p $PERSIST_PATH
          echo "Lưu data tại: $PERSIST_PATH"

      - name: 🐍 Tạo file loop Python (chạy nền 24/7)
        script: |
          cat > $LOOP_FILE <<'PYCODE'
          import os, time, datetime, json

          DATA_PATH = os.environ.get("PERSIST_PATH", "/Users/builder/.persist_data")
          LOG_FILE = os.path.join(DATA_PATH, "loop_log.json")

          print("🌀 VPS Loop Runner khởi động...")

          while True:
              now = datetime.datetime.now().isoformat()
              print(f"[{now}] Hệ thống hoạt động ổn định.")
              
              with open(LOG_FILE, "a") as f:
                  f.write(json.dumps({"time": now, "status": "running"}) + "\n")

              time.sleep(60)
          PYCODE

      - name: 🔁 Giữ tiến trình chạy 24/7 (auto-restart)
        script: |
          echo "🚀 Bắt đầu loop chạy nền"
          while true; do
            python3 $LOOP_FILE || echo "⚠️ Loop dừng — khởi động lại sau 5s"
            sleep 5
          done
