name: macOS Built-in VNC

on:
  workflow_dispatch:

jobs:
  vnc-job:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: Enable VNC Server (Screen Sharing)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -restart -agent -privs -all
          # 设置密码 (ví dụ: 123456)
          echo "123456" | sudo tee /Library/Preferences/com.apple.VNCSettings.txt > /dev/null
          echo "✅ VNC server 已启用，密码: 123456"

      - name: Open reverse SSH tunnel (Pinggy, show URL)
        run: |
          while true; do
            ssh -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 \
              -R0:localhost:5900 tcp@a.pinggy.io || true
            sleep 20
          done &

      - name: Keepalive
        run: |
          for i in {1..300}; do
            echo "⏳ Runner alive step $i ..."
            sleep 60
          done
