name: macOS VNC Blender

on:
  workflow_dispatch:

jobs:
  vnc-job:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: Tạo user blender với mật khẩu 123456Hi
        run: |
          # Tạo user blender
          sudo dscl . -create /Users/blender
          sudo dscl . -create /Users/blender UserShell /bin/bash
          sudo dscl . -create /Users/blender RealName "Blender User"
          sudo dscl . -create /Users/blender UniqueID 511
          sudo dscl . -create /Users/blender PrimaryGroupID 20
          sudo dscl . -create /Users/blender NFSHomeDirectory /Users/blender
          sudo dscl . -passwd /Users/blender 123456Hi
          sudo createhomedir -c -u blender > /dev/null
          echo "✅ Đã tạo user blender / pass=123456Hi"

      - name: Bật VNC server (Screen Sharing) và thêm quyền cho blender
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -restart -agent -privs -all

          # Thêm user blender vào danh sách Remote Management
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -allowAccessFor -specifiedUsers
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -access -on -users blender -privs -all

          echo "✅ VNC đã bật (dùng user=blender, pass=123456Hi)"

      - name: Mở tunnel VNC qua Pinggy (hiện URL)
        run: |
          while true; do
            ssh -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 \
              -R0:localhost:5900 tcp@a.pinggy.io || true
            sleep 20
          done &

      - name: Keep alive
        run: |
          for i in {1..300}; do
            echo "⏳ Runner alive $i ..."
            sleep 60
          done
