name: macOS VNC Runner

on:
  workflow_dispatch:

jobs:
  vnc-job:
    runs-on: macos-latest
    timeout-minutes: 350

    steps:
      - name: Đặt mật khẩu cho user runner
        run: |
          echo "runner:123456Hi" | sudo chpasswd
          echo "✅ Đã đặt mật khẩu cho user 'runner'"

      - name: Bật VNC server (Screen Sharing)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -restart -agent -privs -all

          # Bật legacy VNC password (dùng để cho phép client nhập pass)
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvnclegacy -vnclegacy yes \
            -setvncpw 123456Hi

          echo "✅ VNC server đã bật: user=runner, pass=123456Hi"

      - name: Mở tunnel VNC qua Pinggy (sẽ in URL/IP)
        run: |
          while true; do
            ssh -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 \
              -R0:localhost:5900 tcp@a.pinggy.io || true
            sleep 20
          done &

      - name: Giữ job sống
        run: |
          for i in {1..300}; do
            echo "⏳ Runner alive step $i ..."
            sleep 60
          done
